# Tokyo Night
format = """
[░▒▓](#a3aed2)\
[ $os ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
$nix_shell\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[os]
disabled = false
style = "bg:#a3aed2 fg:#090c0c" # Style to match the segment it's in
format = "[$symbol]($style)" # Display only the symbol, styled

[os.symbols]
NixOS = ""   # NixOS logo
Macos = "󰀵"   # Apple logo
Linux = ""   # Tux (Linux penguin)
Windows = "" # Windows logo

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[nix_shell]
symbol = "󱄅 " # Nix flake icon with a space
style = "bg:#212736" # Style to match the segment for dev tools
format = '[[ $symbol$state${name:+ ($name)} ](fg:#769ff0 bg:#212736)]($style)' # Shows state (e.g. pure, develop) and name if available
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
#
# format = """
# [](#9A348E)\
# $os\
# $username\
# [](bg:#DA627D fg:#9A348E)\
# $directory\
# [](fg:#DA627D bg:#FCA17D)\
# $git_branch\
# $git_status\
# [](fg:#FCA17D bg:#86BBD8)\
# $c\
# $elixir\
# $elm\
# $golang\
# $gradle\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# $scala\
# [](fg:#86BBD8 bg:#06969A)\
# $docker_context\
# [](fg:#06969A bg:#33658A)\
# $time\
# [ ](fg:#33658A)\
# """
#
# # Disable the blank line at the start of the prompt
# # add_newline = false
#
# # You can also replace your username with a neat symbol like   or disable this
# # and use the os module below
# [username]
# show_always = true
# style_user = "bg:#9A348E"
# style_root = "bg:#9A348E"
# format = '[$user ]($style)'
# disabled = false
#
# # An alternative to the username module which displays a symbol that
# # represents the current operating system
# [os]
# style = "bg:#9A348E"
# disabled = true # Disabled by default
#
# [directory]
# style = "bg:#DA627D"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"
#
# # Here is how you can shorten some long paths by text replacement
# # similar to mapped_locations in Oh My Posh:
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
# # Keep in mind that the order matters. For example:
# # "Important Documents" = " 󰈙 "
# # will not be replaced, because "Documents" was already substituted before.
# # So either put "Important Documents" before "Documents" or use the substituted version:
# # "Important 󰈙 " = " 󰈙 "
#
# [c]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [docker_context]
# symbol = " "
# style = "bg:#06969A"
# format = '[ $symbol $context ]($style)'
#
# [elixir]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [elm]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [git_branch]
# symbol = ""
# style = "bg:#FCA17D"
# format = '[ $symbol $branch ]($style)'
#
# [git_status]
# style = "bg:#FCA17D"
# format = '[$all_status$ahead_behind ]($style)'
#
# [golang]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [gradle]
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [haskell]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [java]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [julia]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [nodejs]
# symbol = ""
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [nim]
# symbol = "󰆥 "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [rust]
# symbol = ""
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [scala]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#33658A"
# format = '[ ♥ $time ]($style)'
